using AutoMapper;
using ASI.Basecode.Data.Models;
using ASI.Basecode.Services.ServiceModels;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;
using System.Globalization;

namespace ASI.Basecode.WebApp
{
    // AutoMapper configuration
    internal partial class StartupConfigurer
    {
        /// <summary>
        /// Configure auto mapper
        /// </summary>
        private void ConfigureAutoMapper()
        {
            var mapperConfiguration = new MapperConfiguration(config =>
            {
                config.AddProfile(new AutoMapperProfileConfiguration());
            });

            this._services.AddSingleton<IMapper>(sp => mapperConfiguration.CreateMapper());
        }

        private class AutoMapperProfileConfiguration : Profile
        {
            public AutoMapperProfileConfiguration()
            {
                CreateMap<UserViewModel, User>();
                CreateMap<User, UserViewModel>();
                CreateMap<ProfileViewModel, User>();

                // Add mapping between RoomViewModel and Room
                CreateMap<RoomViewModel, Room>()
                    .ForMember(dest => dest.RoomAmenities, opt => opt.Ignore()) // Ignore RoomAmenities manually updated content on db through service
                    .ForMember(dest => dest.RoomId, opt => opt.MapFrom(src => src.RoomId)) // Ignore RoomId autogenerated
                    .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
                    .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
                    .ForMember(dest => dest.UpdatedDate, opt => opt.MapFrom(src => DateTime.Now)) // Set UpdatedDate on update
                    .ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)) // Assuming you get userId in RoomViewModel
                    .ForMember(dest => dest.IsDeleted, opt => opt.Ignore());
                CreateMap<Room, RoomViewModel>();

                
                CreateMap<RoomAmenityViewModel, RoomAmenity>();
                CreateMap<AmenityViewModel, Amenity>();
                CreateMap<ImageViewModel, Image>();
                CreateMap<BookingViewModel, Booking>()
                    .ForMember(dest => dest.CheckInTime,
                opt => opt.MapFrom(src =>
                    BookingViewModel.ParseTimeSpan(src.CheckInTimeString)
                    ))
            .ForMember(dest => dest.CheckOutTime,
                opt => opt.MapFrom(src =>
                    BookingViewModel.ParseTimeSpan(src.CheckOutTimeString)
                    ));
                CreateMap<Booking, BookingViewModel>()
                    .ForMember(dest => dest.SelectedDays, opt => opt.MapFrom(src => string.Join(",", src.RecurringBookings.Select(x => x.Day))))
                    .ForMember(dest => dest.CheckInTimeString,
                        opt => opt.MapFrom(src => Booking.FormatTime(src.CheckInTime)))
                    .ForMember(dest => dest.CheckOutTimeString,
                        opt => opt.MapFrom(src => Booking.FormatTime(src.CheckOutTime)));
                CreateMap<RecurringBookingViewModel, RecurringBooking>();
                CreateMap<RecurringBooking, RecurringBookingViewModel>();
            }
        }
    }
}
